"""empty message

Revision ID: 094a8c6a885d
Revises: 541746a7bbd1
Create Date: 2025-02-01 22:49:32.833242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094a8c6a885d'
down_revision = '541746a7bbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_debt_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_debt_lender_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_debt_lender_id'), ['lender_id', 'borrower_id', 'group_debt_id'])
        batch_op.create_foreign_key(batch_op.f('fk_debt_group_debt_id_group_debt'), 'group_debt', ['group_debt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_debt_group_debt_id_group_debt'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_debt_lender_id'), type_='unique')
        batch_op.create_unique_constraint('uq_debt_lender_id', ['lender_id', 'borrower_id'])
        batch_op.drop_column('group_debt_id')

    # ### end Alembic commands ###
