"""empty message

Revision ID: 1234b8ba3617
Revises: f10e4e6b6e12
Create Date: 2025-03-07 22:55:08.614441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1234b8ba3617'
down_revision = 'f10e4e6b6e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split', sa.Enum('AMOUNT', 'EQUALLY', 'PERCENTAGE', name='splittype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('split')

    # ### end Alembic commands ###
