"""empty message

Revision ID: 134b83db4dfe
Revises: ade9cd0f5043
Create Date: 2025-03-13 18:43:44.747894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134b83db4dfe'
down_revision = 'ade9cd0f5043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name=op.f('fk_friend_association_friend_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_friend_association_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', name=op.f('pk_friend_association'))
    )
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('friend_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='fk_friends_friend_id_user'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_friends_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', name='pk_friends')
    )
    op.drop_table('friend_association')
    # ### end Alembic commands ###
