"""empty message

Revision ID: 3cebaac48034
Revises: 64dc258ef700
Create Date: 2025-02-01 22:17:52.881149

"""
from alembic import op
import sqlalchemy as sa
from app.database import naming_convention


# revision identifiers, used by Alembic.
revision = '3cebaac48034'
down_revision = '64dc258ef700'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_unique_constraint(None, ['lender_id', 'borrower_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
