"""empty message

Revision ID: 541746a7bbd1
Revises: 3cebaac48034
Create Date: 2025-02-01 22:35:04.448839

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '541746a7bbd1'
down_revision = '3cebaac48034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    # ### end Alembic commands ###
